[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]

[rpc_endpoints]
xrpl_testnet = "https://rpc.testnet.xrplevm.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
